function VenturiTubeS3012 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  VENTURITUBES3012 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  VENTURITUBES3012 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  VenturiTubeS3012 = importfile("/Users/matthewj/Documents/GitHub/ASEN_2002_Lab1/Lab_2/selected_data/VenturiTube_S301_2.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Nov-2020 18:28:44

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["AtmosphericPressurePa", "AtmosphericTemperatureK", "Var3", "Var4", "Var5", "Var6", "Var7"];
opts.SelectedVariableNames = ["AtmosphericPressurePa", "AtmosphericTemperatureK"];
opts.VariableTypes = ["double", "double", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var3", "Var4", "Var5", "Var6", "Var7"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var3", "Var4", "Var5", "Var6", "Var7"], "EmptyFieldRule", "auto");

% Import the data
VenturiTubeS3012 = readtable(filename, opts);

end